
name: OWTF CI


on:

  push:
    branches: [ master, develop, github_actions ]
  pull_request:
    branches: [ master, develop, github_actions ]


  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.9 ]
        node-version: [ 15.0 ]
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: owtf_db_user
          POSTGRES_PASSWORD: jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=
          POSTGRES_DB: owtf_db
        ports:
          - 5432:5432
        options: >-
          --name=postgres
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    
    steps:
    
      - uses: actions/checkout@v2

      - name: before_install
        run: |
          sudo apt update
          sudo apt -y install libffi-dev golang postgresql-client libgnutls28-dev libyaml-dev python3-yaml python3-pip libcurl4-openssl-dev libssl-dev
          sudo pip3 install pyopenssl
        
      - name: install
        run: |
          echo "Running install base requirements"
          sudo pip3 install -r requirements/base.txt
          echo "Running install test requirements"
          sudo pip3 install -r requirements/test.txt
          echo "create virtual environment"
          sudo python3 -m venv $WORKSPACE/.virtualenvs/owtf --clear
          echo "Activate virtual environment"
          sudo su
          source $WORKSPACE/.virtualenvs/owtf/bin/activate
          echo "Running setup.py"
          echo '\n\n' | sudo python3 setup.py develop
      - name: before_script
        run: |
          sudo source $WORKSPACE/.virtualenvs/owtf/bin/activate
          sudo pip3 install mock pyHamcrest
          sudo cp -f ./tests/fixtures/profiles/plugin_web/groups.cfg ~/.owtf/conf/profiles/plugin_web/groups.cfg
          sudo cp -f ./tests/fixtures/profiles/plugin_net/groups.cfg ~/.owtf/conf/profiles/plugin_net/groups.cfg
          sudo cp -f ./tests/fixtures/profiles/plugin_aux/groups.cfg ~/.owtf/conf/profiles/plugin_aux/groups.cfg
          git config --global user.email "tasty@mac.test"
          git config --global user.name "Tasty Test"

      - name: Python_tests_step
        run: |
          source $WORKSPACE/.virtualenvs/owtf/bin/activate
          sudo python3 -m unittest tests.functional.cli.test_empty_run
          sudo python3 -m unittest tests.functional.cli.test_list_plugins
          sudo python3 -m unittest tests.functional.cli.test_nowebui
          sudo python3 -m unittest tests.functional.plugins.web
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

