
name: OWTF CI


on:

  push:
    branches: [ master, develop, github_actions ]
  pull_request:
    branches: [ master, develop, github_actions ]


  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.9 ]
        node-version: [ 15.0 ]
    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: owtf_db_user
          POSTGRES_PASSWORD: jgZKW33Q+HZk8rqylZxaPg1lbuNGHJhgzsq3gBKV32g=
          POSTGRES_DB: owtf_db
        ports:
          - 5432:5432
        options: >-
          --name=postgres
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    
    steps:
    
      - uses: actions/checkout@v2

      - name: before_install
        run: |
          apt update
          apt -y install libffi-dev golang postgresql-client libgnutls28-dev libyaml-dev python3-yaml python3-pip 
          pip3 install pyopenssl
        
      - name: install
        run: |
          pip3 install -r requirements/base.txt
          pip3 install -r requirements/test.txt
          echo '\n\n' | python setup.py develop
      - name: before_script
        run: |
          pip3 install mock pyHamcrest
          cp -f ./tests/fixtures/profiles/plugin_web/groups.cfg ~/.owtf/conf/profiles/plugin_web/groups.cfg
          cp -f ./tests/fixtures/profiles/plugin_net/groups.cfg ~/.owtf/conf/profiles/plugin_net/groups.cfg
          cp -f ./tests/fixtures/profiles/plugin_aux/groups.cfg ~/.owtf/conf/profiles/plugin_aux/groups.cfg
          git config --global user.email "tasty@mac.test"
          git config --global user.name "Tasty Test"

      - name: Python_tests_step
        run: |
          python3 -m unittest tests.functional.cli.test_empty_run
          python3 -m unittest tests.functional.cli.test_list_plugins
          python3 -m unittest tests.functional.cli.test_nowebui
          python3 -m unittest tests.functional.plugins.web
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432

      - name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
        run: yarn test
        working-directory: owtf/webapp
